name: flutter_flavorizr
description: A flutter utility to easily create flavors in your flutter application
version: 1.0.9
repository: https://github.com/AngeloAvv/flutter_flavorizr
issue_tracker: https://github.com/AngeloAvv/flutter_flavorizr/issues
homepage: https://www.angelocassano.it

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.1.2
  args: ^2.0.0
  checked_yaml: ^1.0.2
  io: ^0.3.4
  json_annotation: ^4.0.0
  xml: ^4.1.0
  yaml: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
